### ISSUE TITLE
Blue border around text

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/landing-page#1]
###  @Dawroun Ilmhub.uz landing pagedagi text atrofide hunuk Blue Border paydo bo'lyapti.

How to reproduce:
- go to ilmhub.uz and see the text with big font. It has blue border. Blue border disappears when you touch anywhere else on the screen. If you touch the Banner text, blue border appears again.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/30383473/147857481-63160310-bd26-4887-8c10-87b50f53ebca.png">

How to fix:
- try inspecting and giving border: none; to some elements there

> Ask Umid for help if you cant figure out.

**Comment by Dawroun** [comment]
Okay, man yoqotib qoyaman,  faqat, man clone qivolib ochganimda manda chiqmayapti u border

**Comment by wahid-d** [comment]
@Dawroun do these commands before starting the fix:
- clone repo
- make sure you r on dev
- `git pull`
- `git checkout -b davron/bug-1`

**Comment by wahid-d** [comment]
Clone qilib run qildingmi? Qanday run qilding?

**Comment by wahid-d** [comment]
Fixed by @shahbozkhurramov
