### ISSUE TITLE
Suggest content for feedback section

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/landing-page#3]
### Feedback section

Brainstorm for ideas to fill the "Feedback section" of the page.
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/30383473/147858874-e909eb8b-6230-449e-bfa0-8929aba64481.png">

We have to fill those feedback texts with something. Prepare some good suggestions.

**Comment by Rizo11** [comment]
Dasturlashlashni men avval o'zim YouTube dan o'rganmoqchi bo'ldim, lekin ma'lumot ko'pligi tufayli nimadan boshlashni bilmadim. IlmHub ga kelganimda malakali ustozlar menga to'g'ri yo'l ko'rsatishdi va sifatli ta'lim berishdi.


Universitetimni 1-kursida o'tgan mavzularni, 5 oy ichida to'liq o'rgandim. Bundan juda hursandman.


Menga talabchan ustozlar kerak edi, chunki meni kimdir doim o'qishga undab turmasa o'qimas edim. Bu o'quv markaziga kelib men qidirgan ustozlarni topdim.


.NET bootcamp menga dasturlash sohasida junior darajaga chiqishimda juda katta yordam berdi, chunki oz vaqt davomida ko'p narsalarni sifatli tarzda o'rgatishdi. Darslar 5/7 bo'ldani uchun, kunimni 70% qismi markazdagi co-workingda boshqa do'stlarim bilan o'tdi. Bu orqali ham dasturlashni ham networkingni o'rgandim.


Foundation & Algorithm darsini olganimdan kegin 1 oydan so'ng, to'g'risi, afsuslandim. "Axir bu bilimlar menga hech qanaqasiga web site yaratish uchun kerak bo'lmaydi-ku" - deb o'ylardim. Lekin baribir o'qidim. Hozir, 2 oydan so'ng .NET MVC kursini tugataman, va Foundation & Algorithm darslaridan olgan bilimlarim suv va havodek kerak bo'lyapti, chunki ularda men nafaqat muammolarni yechish, balki muammolarni samarali tarzda yechish qobiliyatlarini o'zimda shakillantirdim. Sizlarga maslahatim, darsturlashni Foundation & Algorithm dan boshlang.
