### ISSUE TITLE
Loading view

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/landing-page#52]
Add some loading view with our logo doing some animation. You can use css animations.

**Comment by wahid-d** [comment]
@shahbozkhurramov Mana bu issue ustida ishlayapsizmi yoki yopildimi?

**Comment by shahbozkhurramov** [comment]
> @shahbozkhurramov Mana bu issue ustida ishlayapsizmi yoki yopildimi?
> 

Ishlanyapti yopilgani yoq
