### ISSUE TITLE
Dark Mode.

### ISSUE THREAD

**Issue by wahid-d** [ilmhub-uz/landing-page#53]
Implement dark mode for the site.

**Comment by wahid-d** [comment]
@shahbozkhurramov Shu issue uchun assetlar so'ragan ediz. Qanday assetlar kerak?

**Comment by shahbozkhurramov** [comment]
> @shahbozkhurramov Shu issue uchun assetlar so'ragan ediz. Qanday assetlar kerak?

Css ichidagi dark style kerak
